#!/bin/bash

# Immediate Mode Check
function query()
{
  FILE_COMPLETE=$1
  grep -n --color=never \
    -e glBegin\( \
    -e glEnd\( \
    -e glVertex[^A] \
    -e glNormal \
    -e glTexCoord \
    -e fdrawline \
    -e fdrawbox \
    -e fdrawbox_filled \
    -e fdrawcheckboard \
    -e sdrawline \
    -e sdrawbox \
    -e UI_ThemeColor \
    -e glColor \
    -e glEnableClientState \
    -e glVertexPointer \
    -e glDisableClientState \
    -e glRect \
    $FILE_COMPLETE
}

if [ "$1" == "" ] ; then
  echo "No file specified. Use: `query filename.c`. Exiting."
  exit 0
fi

FILE=`find . -name $1`

if [ "$FILE"  == "" ]; then
  echo "File not found!"
  exit 0
fi

echo -e "Querying file:\n$FILE\n"
query $FILE
